# qmake project generated by QMsDev
#
# General settings


TEMPLATE = lib
CONFIG  += qt warn_off staticlib opengl create_prl
TARGET  += CardinalBSpline

INCLUDEPATH += ../Blurmaps
INCLUDEPATH += ../PDBParser
INCLUDEPATH += ../UsefulMath
#INCLUDEPATH += ../Geometry

# Input

SOURCES =  \
	        Bbasis.cpp \
                CardinalBSpline.cpp
HEADERS =  \
		Bbasis.h \
		CardinalBSpline.h 
